# Generated by Django 2.1.1 on 2018-10-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=30, verbose_name='姓名')),
                ('UID', models.CharField(max_length=30, unique=True, verbose_name='UID')),
                ('CardID', models.CharField(help_text='Example:D0987654', max_length=30, unique=True, verbose_name='Student ID')),
                ('SEX', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=30, verbose_name='性别')),
                ('TEL', models.CharField(blank=True, max_length=30, verbose_name='联系方式')),
                ('NOTE', models.CharField(blank=True, max_length=30, verbose_name='备注')),
                ('TIME', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CardID',
                'verbose_name_plural': '學生資料',
            },
        ),
    ]
