# Generated by Django 2.1.1 on 2018-10-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
